In [440]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import pickle
EXPORT_PATH = '../data/processed/'
DATA_PATH = '../data/raw/'

In [441]:
df=pd.read_csv(DATA_PATH +'survey_results_public.csv')

df.shape

(64461, 61)

In [442]:
df.sample(1).T

                                                                          26108
Respondent                                                                26204
MainBranch                    I am not primarily a developer, but I write co...
Hobbyist                                                                    Yes
Age                                                                        56.0
Age1stCode                                                                   11
CompFreq                                                                Monthly
CompTotal                                                                8000.0
ConvertedComp                                                           96000.0
Country                                                           United States
CurrencyDesc                                               United States dollar
CurrencySymbol                                                              USD
DatabaseDesireNextYear        Elasticsearch;Microsoft SQL Server;MySQL;Postg...
DatabaseWorkedWith                                   Microsoft SQL Server;MySQL
DevType                       Data or business analyst;Developer, full-stack...
EdLevel                         Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
Employment                    Independent contractor, freelancer, or self-em...
Ethnicity                                          White or of European descent
Gender                                                                      Man
JobFactors                    How widely used or impactful my work output wo...
JobSat                                                       Slightly satisfied
JobSeek                       I’m not actively looking, but I am open to new...
LanguageDesireNextYear        Bash/Shell/PowerShell;C#;C++;HTML/CSS;JavaScri...
LanguageWorkedWith                    C;C#;C++;HTML/CSS;Java;JavaScript;SQL;VBA
MiscTechDesireNextYear                    .NET;.NET Core;Hadoop;Node.js;Xamarin
MiscTechWorkedWith                                               .NET;.NET Core
NEWCollabToolsDesireNextYear        Github;Slack;Google Suite (Docs, Meet, etc)
NEWCollabToolsWorkedWith      Confluence;Jira;Github;Gitlab;Slack;Trello;Goo...
NEWDevOps                                                                    No
NEWDevOpsImpt                                               Extremely important
NEWEdImpt                                                        Very important
NEWJobHunt                    Having a bad day (or week or month) at work;Wa...
NEWJobHuntResearch            Read company media, such as employee blogs or ...
NEWLearn                                                   Once every few years
NEWOffTopic                                                            Not sure
NEWOnboardGood                                     Onboarding? What onboarding?
NEWOtherComms                                                                No
NEWOvertime                   Sometimes: 1-2 days per month but less than we...
NEWPurchaseResearch           Start a free trial;Ask developers I know/work ...
NEWPurpleLink                                                 Hello, old friend
NEWSOSites                    Stack Overflow (public Q&A for anyone who code...
NEWStuck                      Meditate;Visit Stack Overflow;Do other work an...
OpSys                                                                   Windows
OrgSize                                                        2 to 9 employees
PlatformDesireNextYear              Docker;Microsoft Azure;Raspberry Pi;Windows
PlatformWorkedWith            Docker;Kubernetes;Linux;Raspberry Pi;Windows;W...
PurchaseWhat                                                                NaN
Sexuality                                               Straight / Heterosexual
SOAccount                                                                   Yes
SOComm                                                            Yes, somewhat
SOPartFreq                                  Less than once per month or monthly
SOVisitFreq                                     A few times per month or weekly
SurveyEase                                           Neither easy nor difficult
SurveyLength                                              Appropriate in length
Trans                                                                        No
UndergradMajor                Computer science, computer engineering, or sof...
WebframeDesireNextYear                        Angular.js;jQuery;React.js;Spring
WebframeWorkedWith                                                          NaN
WelcomeChange                           Just as welcome now as I felt last year
WorkWeekHrs                                                                65.0
YearsCode                                                                    42
YearsCodePro                                                                 39

In [443]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Respondent                    64461 non-null  int64
 1   MainBranch                    64162 non-null  object
 2   Hobbyist                      64416 non-null  object
 3   Age                           45446 non-null  float64
 4   Age1stCode                    57900 non-null  object
 5   CompFreq                      40069 non-null  object
 6   CompTotal                     34826 non-null  float64
 7   ConvertedComp                 34756 non-null  float64
 8   Country                       64072 non-null  object
 9   CurrencyDesc                  45472 non-null  object
 10  CurrencySymbol                45472 non-null  object
 11  DatabaseDesireNextYear        44070 non-null  object
 12  DatabaseWorkedWith            49537 non-null  object
 13  DevType                       49370 non-null  object
 14  EdLevel                       57431 non-null  object
 15  Employment                    63854 non-null  object
 16  Ethnicity                     45948 non-null  object
 17  Gender                        50557 non-null  object
 18  JobFactors                    49349 non-null  object
 19  JobSat                        45194 non-null  object
 20  JobSeek                       51727 non-null  object
 21  LanguageDesireNextYear        54113 non-null  object
 22  LanguageWorkedWith            57378 non-null  object
 23  MiscTechDesireNextYear        42379 non-null  object
 24  MiscTechWorkedWith            40314 non-null  object
 25  NEWCollabToolsDesireNextYear  47287 non-null  object
 26  NEWCollabToolsWorkedWith      52883 non-null  object
 27  NEWDevOps                     42686 non-null  object
 28  NEWDevOpsImpt                 41732 non-null  object
 29  NEWEdImpt                     48465 non-null  object
 30  NEWJobHunt                    42286 non-null  object
 31  NEWJobHuntResearch            41022 non-null  object
 32  NEWLearn                      56156 non-null  object
 33  NEWOffTopic                   50804 non-null  object
 34  NEWOnboardGood                42623 non-null  object
 35  NEWOtherComms                 57205 non-null  object
 36  NEWOvertime                   43231 non-null  object
 37  NEWPurchaseResearch           37321 non-null  object
 38  NEWPurpleLink                 54803 non-null  object
 39  NEWSOSites                    58275 non-null  object
 40  NEWStuck                      54983 non-null  object
 41  OpSys                         56228 non-null  object
 42  OrgSize                       44334 non-null  object
 43  PlatformDesireNextYear        50605 non-null  object
 44  PlatformWorkedWith            53843 non-null  object
 45  PurchaseWhat                  39364 non-null  object
 46  Sexuality                     43992 non-null  object
 47  SOAccount                     56805 non-null  object
 48  SOComm                        56476 non-null  object
 49  SOPartFreq                    46792 non-null  object
 50  SOVisitFreq                   56970 non-null  object
 51  SurveyEase                    51802 non-null  object
 52  SurveyLength                  51701 non-null  object
 53  Trans                         49345 non-null  object
 54  UndergradMajor                50995 non-null  object
 55  WebframeDesireNextYear        40024 non-null  object
 56  WebframeWorkedWith            42279 non-null  object
 57  WelcomeChange                 52683 non-null  object
 58  WorkWeekHrs                   41151 non-null  float64
 59  YearsCode                     57684 non-null  object
 60  YearsCodePro                  46349 non-null  object
dtypes: float64(4), int64(1), object(56)
memory usage: 30.0+ MB

In [444]:
df.describe()

         Respondent           Age      CompTotal  ConvertedComp   WorkWeekHrs
count  64461.000000  45446.000000   3.482600e+04   3.475600e+04  41151.000000
mean   32554.079738     30.834111  3.190464e+242   1.037561e+05     40.782174
std    18967.442360      9.585392            inf   2.268853e+05     17.816383
min        1.000000      1.000000   0.000000e+00   0.000000e+00      1.000000
25%    16116.000000     24.000000   2.000000e+04   2.464800e+04     40.000000
50%    32231.000000     29.000000   6.300000e+04   5.404900e+04     40.000000
75%    49142.000000     35.000000   1.250000e+05   9.500000e+04     44.000000
max    65639.000000    279.000000  1.111111e+247   2.000000e+06    475.000000

In [445]:
col = ['YearsCode','YearsCodePro']

for c in col:
    print(c)    
    print(df[c].unique())
    print('----------------------------')

YearsCode
['36' '7' '4' '15' '6' '17' '8' '10' '35' '5' '37' '19' '9' '22' '30' '23'
 '20' '2' 'Less than 1 year' '3' '13' '25' '16' '43' '11' '38' '33' nan
 '24' '21' '12' '40' '27' '50' '46' '14' '18' '28' '32' '44' '26' '42'
 '31' '34' '29' '1' '39' '41' '45' 'More than 50 years' '47' '49' '48']
----------------------------
YearsCodePro
['27' '4' nan '8' '13' '2' '7' '20' '1' '23' '3' '12' '17' '18' '10' '14'
 '29' '6' '28' '9' '15' '11' '16' '25' 'Less than 1 year' '5' '21' '19'
 '35' '24' '32' '22' '30' '38' '26' '40' '33' '31' 'More than 50 years'
 '34' '36' '39' '37' '41' '45' '47' '42' '46' '50' '43' '44' '48' '49']
----------------------------

In [446]:
dict = {'Less than 1 year':0, 'More than 50 years':51}

for c in col:
    df.replace({c:dict},inplace=True)



df['YearsCode']=df['YearsCode'].astype(float)
df['YearsCodePro']=df['YearsCodePro'].astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64461 entries, 0 to 64460
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Respondent                    64461 non-null  int64
 1   MainBranch                    64162 non-null  object
 2   Hobbyist                      64416 non-null  object
 3   Age                           45446 non-null  float64
 4   Age1stCode                    57900 non-null  object
 5   CompFreq                      40069 non-null  object
 6   CompTotal                     34826 non-null  float64
 7   ConvertedComp                 34756 non-null  float64
 8   Country                       64072 non-null  object
 9   CurrencyDesc                  45472 non-null  object
 10  CurrencySymbol                45472 non-null  object
 11  DatabaseDesireNextYear        44070 non-null  object
 12  DatabaseWorkedWith            49537 non-null  object
 13  DevType                       49370 non-null  object
 14  EdLevel                       57431 non-null  object
 15  Employment                    63854 non-null  object
 16  Ethnicity                     45948 non-null  object
 17  Gender                        50557 non-null  object
 18  JobFactors                    49349 non-null  object
 19  JobSat                        45194 non-null  object
 20  JobSeek                       51727 non-null  object
 21  LanguageDesireNextYear        54113 non-null  object
 22  LanguageWorkedWith            57378 non-null  object
 23  MiscTechDesireNextYear        42379 non-null  object
 24  MiscTechWorkedWith            40314 non-null  object
 25  NEWCollabToolsDesireNextYear  47287 non-null  object
 26  NEWCollabToolsWorkedWith      52883 non-null  object
 27  NEWDevOps                     42686 non-null  object
 28  NEWDevOpsImpt                 41732 non-null  object
 29  NEWEdImpt                     48465 non-null  object
 30  NEWJobHunt                    42286 non-null  object
 31  NEWJobHuntResearch            41022 non-null  object
 32  NEWLearn                      56156 non-null  object
 33  NEWOffTopic                   50804 non-null  object
 34  NEWOnboardGood                42623 non-null  object
 35  NEWOtherComms                 57205 non-null  object
 36  NEWOvertime                   43231 non-null  object
 37  NEWPurchaseResearch           37321 non-null  object
 38  NEWPurpleLink                 54803 non-null  object
 39  NEWSOSites                    58275 non-null  object
 40  NEWStuck                      54983 non-null  object
 41  OpSys                         56228 non-null  object
 42  OrgSize                       44334 non-null  object
 43  PlatformDesireNextYear        50605 non-null  object
 44  PlatformWorkedWith            53843 non-null  object
 45  PurchaseWhat                  39364 non-null  object
 46  Sexuality                     43992 non-null  object
 47  SOAccount                     56805 non-null  object
 48  SOComm                        56476 non-null  object
 49  SOPartFreq                    46792 non-null  object
 50  SOVisitFreq                   56970 non-null  object
 51  SurveyEase                    51802 non-null  object
 52  SurveyLength                  51701 non-null  object
 53  Trans                         49345 non-null  object
 54  UndergradMajor                50995 non-null  object
 55  WebframeDesireNextYear        40024 non-null  object
 56  WebframeWorkedWith            42279 non-null  object
 57  WelcomeChange                 52683 non-null  object
 58  WorkWeekHrs                   41151 non-null  float64
 59  YearsCode                     57684 non-null  float64
 60  YearsCodePro                  46349 non-null  float64
dtypes: float64(6), int64(1), object(54)
memory usage: 30.0+ MB

In [447]:
df.describe()

,Respondent,Age,CompTotal,ConvertedComp,WorkWeekHrs,YearsCode,YearsCodePro
count,64461.000000,45446.000000,3.482600e+04,3.475600e+04,41151.000000,57684.000000,46349.000000
mean,32554.079738,30.834111,3.190464e+242,1.037561e+05,40.782174,12.709053,8.491812
std,18967.442360,9.585392,inf,2.268853e+05,17.816383,9.717353,7.905296
min,1.000000,1.000000,0.000000e+00,0.000000e+00,1.000000,0.000000,0.000000
25%,16116.000000,24.000000,2.000000e+04,2.464800e+04,40.000000,6.000000,3.000000
50%,32231.000000,29.000000,6.300000e+04,5.404900e+04,40.000000,10.000000,6.000000
75%,49142.000000,35.000000,1.250000e+05,9.500000e+04,44.000000,17.000000,12.000000
max,65639.000000,279.000000,1.111111e+247,2.000000e+06,475.000000,51.000000,51.000000

### split multi answers

In [448]:
def split_answer(answer , sep=';'):
    
    def check_delimiter(x):
        return x.str.contains(sep)
    
    if check_delimiter(answer).any():
        modf =answer.str.split(sep)
        mask = modf.isna()
        modf[mask]=modf[mask].apply(lambda x: '')
        return modf
    else:
        return answer

In [449]:
object_cols = df.select_dtypes(include='object').columns.tolist()
for col in object_cols:
    df[col] = split_answer(df[col])

In [450]:
df.sample(1).T

                                                                          59233
Respondent                                                                60409
MainBranch                    I am not primarily a developer, but I write co...
Hobbyist                                                                    Yes
Age                                                                        51.0
Age1stCode                                                                   18
CompFreq                                                                Monthly
CompTotal                                                              500000.0
ConvertedComp                                                           59316.0
Country                                                                   Kenya
CurrencyDesc                                                    Kenyan shilling
CurrencySymbol                                                              KES
DatabaseDesireNextYear                                         [MongoDB, MySQL]
DatabaseWorkedWith                                             [MongoDB, MySQL]
DevType                                                 [Developer, full-stack]
EdLevel                         Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
Employment                                                   Employed full-time
Ethnicity                                         [Black or of African descent]
Gender                                                                    [Man]
JobFactors                    [Languages, frameworks, and other technologies...
JobSat                                                    Slightly dissatisfied
JobSeek                            I am not interested in new job opportunities
LanguageDesireNextYear            [Bash/Shell/PowerShell, HTML/CSS, JavaScript]
LanguageWorkedWith                [Bash/Shell/PowerShell, HTML/CSS, JavaScript]
MiscTechDesireNextYear                                                [Node.js]
MiscTechWorkedWith                                                    [Node.js]
NEWCollabToolsDesireNextYear           [Github, Google Suite (Docs, Meet, etc)]
NEWCollabToolsWorkedWith               [Github, Google Suite (Docs, Meet, etc)]
NEWDevOps                                                                    No
NEWDevOpsImpt                                               Extremely important
NEWEdImpt                                                      Fairly important
NEWJobHunt                    [Better compensation, Better work/life balance...
NEWJobHuntResearch            [Read company media, such as employee blogs or...
NEWLearn                                                   Once every few years
NEWOffTopic                                                            Not sure
NEWOnboardGood                                                               No
NEWOtherComms                                                                No
NEWOvertime                                    Often: 1-2 days per week or more
NEWPurchaseResearch
NEWPurpleLink                                                            Amused
NEWSOSites                    [Stack Overflow (public Q&A for anyone who cod...
NEWStuck                      [Visit Stack Overflow, Go for a walk or other ...
OpSys                                                               Linux-based
OrgSize                                                1,000 to 4,999 employees
PlatformDesireNextYear                                          [Docker, Linux]
PlatformWorkedWith                                              [Docker, Linux]
PurchaseWhat                                      I have little or no influence
Sexuality                                             [Straight / Heterosexual]
SOAccount                                                                    No
SOComm                                                           No, not really
SOPartFreq                                                                  NaN
SOVisitFreq                                     A few times per month or weekly
SurveyEase                                                                 Easy
SurveyLength                                                           Too long
Trans                                                                        No
UndergradMajor                                        Mathematics or statistics
WebframeDesireNextYear                                                [Express]
WebframeWorkedWith                                                    [Express]
WelcomeChange                           Just as welcome now as I felt last year
WorkWeekHrs                                                                60.0
YearsCode                                                                  35.0
YearsCodePro                                                                NaN

In [451]:
i = df.sample(1).index[0]
df.loc[i,'LanguageWorkedWith']

['HTML/CSS', 'JavaScript']

In [452]:
ind= df.sample(1).index[0]
print(df['DevType'].iloc[i])

['Developer, back-end', 'Developer, front-end', 'Developer, full-stack']

In [453]:
i = df.sample(1).index[0]
print(df['YearsCodePro'].iloc[i])

nan

In [454]:
df.to_pickle(EXPORT_PATH+'1_preprocessed.pkl')